// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/taskmanager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFilter int32

const (
	ListFilter_LIST_FILTER_UNSPECIFIED ListFilter = 0
	ListFilter_LIST_FILTER_ALL         ListFilter = 1
	ListFilter_LIST_FILTER_DONE        ListFilter = 2
	ListFilter_LIST_FILTER_PENDING     ListFilter = 3
)

// Enum value maps for ListFilter.
var (
	ListFilter_name = map[int32]string{
		0: "LIST_FILTER_UNSPECIFIED",
		1: "LIST_FILTER_ALL",
		2: "LIST_FILTER_DONE",
		3: "LIST_FILTER_PENDING",
	}
	ListFilter_value = map[string]int32{
		"LIST_FILTER_UNSPECIFIED": 0,
		"LIST_FILTER_ALL":         1,
		"LIST_FILTER_DONE":        2,
		"LIST_FILTER_PENDING":     3,
	}
)

func (x ListFilter) Enum() *ListFilter {
	p := new(ListFilter)
	*p = x
	return p
}

func (x ListFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_taskmanager_proto_enumTypes[0].Descriptor()
}

func (ListFilter) Type() protoreflect.EnumType {
	return &file_api_proto_taskmanager_proto_enumTypes[0]
}

func (x ListFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListFilter.Descriptor instead.
func (ListFilter) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{0}
}

type SortBy int32

const (
	SortBy_SORT_BY_UNSPECIFIED SortBy = 0
	SortBy_SORT_BY_CREATED     SortBy = 1
	SortBy_SORT_BY_DUE         SortBy = 2
	SortBy_SORT_BY_PRIORITY    SortBy = 3
)

// Enum value maps for SortBy.
var (
	SortBy_name = map[int32]string{
		0: "SORT_BY_UNSPECIFIED",
		1: "SORT_BY_CREATED",
		2: "SORT_BY_DUE",
		3: "SORT_BY_PRIORITY",
	}
	SortBy_value = map[string]int32{
		"SORT_BY_UNSPECIFIED": 0,
		"SORT_BY_CREATED":     1,
		"SORT_BY_DUE":         2,
		"SORT_BY_PRIORITY":    3,
	}
)

func (x SortBy) Enum() *SortBy {
	p := new(SortBy)
	*p = x
	return p
}

func (x SortBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortBy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_taskmanager_proto_enumTypes[1].Descriptor()
}

func (SortBy) Type() protoreflect.EnumType {
	return &file_api_proto_taskmanager_proto_enumTypes[1]
}

func (x SortBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortBy.Descriptor instead.
func (SortBy) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{1}
}

// Timestamps are Unix seconds (UTC). Zero = not set.
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority      string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`               // low, med, high
	DueDate       int64                  `protobuf:"varint,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"` // Unix seconds
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // todo, in-progress, done
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"` // 0 = not completed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Task) GetDueDate() int64 {
	if x != nil {
		return x.DueDate
	}
	return 0
}

func (x *Task) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Task) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type AddTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`               // low, med, high; empty = med
	DueDate       int64                  `protobuf:"varint,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"` // Unix seconds; 0 = none
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTaskRequest) Reset() {
	*x = AddTaskRequest{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskRequest) ProtoMessage() {}

func (x *AddTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskRequest.ProtoReflect.Descriptor instead.
func (*AddTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{1}
}

func (x *AddTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddTaskRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *AddTaskRequest) GetDueDate() int64 {
	if x != nil {
		return x.DueDate
	}
	return 0
}

func (x *AddTaskRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AddTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTaskResponse) Reset() {
	*x = AddTaskResponse{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTaskResponse) ProtoMessage() {}

func (x *AddTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTaskResponse.ProtoReflect.Descriptor instead.
func (*AddTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{2}
}

func (x *AddTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        ListFilter             `protobuf:"varint,1,opt,name=filter,proto3,enum=taskmanager.ListFilter" json:"filter,omitempty"`
	SortBy        SortBy                 `protobuf:"varint,2,opt,name=sort_by,json=sortBy,proto3,enum=taskmanager.SortBy" json:"sort_by,omitempty"`
	DueToday      bool                   `protobuf:"varint,3,opt,name=due_today,json=dueToday,proto3" json:"due_today,omitempty"`
	Overdue       bool                   `protobuf:"varint,4,opt,name=overdue,proto3" json:"overdue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksRequest) GetFilter() ListFilter {
	if x != nil {
		return x.Filter
	}
	return ListFilter_LIST_FILTER_UNSPECIFIED
}

func (x *ListTasksRequest) GetSortBy() SortBy {
	if x != nil {
		return x.SortBy
	}
	return SortBy_SORT_BY_UNSPECIFIED
}

func (x *ListTasksRequest) GetDueToday() bool {
	if x != nil {
		return x.DueToday
	}
	return false
}

func (x *ListTasksRequest) GetOverdue() bool {
	if x != nil {
		return x.Overdue
	}
	return false
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // user these tasks belong to (from JWT sub or metadata)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // todo, in-progress, done
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStatusRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{8}
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{10}
}

type EditTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Priority      *string                `protobuf:"bytes,4,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	DueDate       *int64                 `protobuf:"varint,5,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"` // Unix seconds; 0 = clear
	Status        *string                `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditTaskRequest) Reset() {
	*x = EditTaskRequest{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTaskRequest) ProtoMessage() {}

func (x *EditTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTaskRequest.ProtoReflect.Descriptor instead.
func (*EditTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{11}
}

func (x *EditTaskRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditTaskRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *EditTaskRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *EditTaskRequest) GetPriority() string {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return ""
}

func (x *EditTaskRequest) GetDueDate() int64 {
	if x != nil && x.DueDate != nil {
		return *x.DueDate
	}
	return 0
}

func (x *EditTaskRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type EditTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditTaskResponse) Reset() {
	*x = EditTaskResponse{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTaskResponse) ProtoMessage() {}

func (x *EditTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTaskResponse.ProtoReflect.Descriptor instead.
func (*EditTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{12}
}

type SearchTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTasksRequest) Reset() {
	*x = SearchTasksRequest{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTasksRequest) ProtoMessage() {}

func (x *SearchTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTasksRequest.ProtoReflect.Descriptor instead.
func (*SearchTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{13}
}

func (x *SearchTasksRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SearchTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTasksResponse) Reset() {
	*x = SearchTasksResponse{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTasksResponse) ProtoMessage() {}

func (x *SearchTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTasksResponse.ProtoReflect.Descriptor instead.
func (*SearchTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{14}
}

func (x *SearchTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TagAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagAddRequest) Reset() {
	*x = TagAddRequest{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagAddRequest) ProtoMessage() {}

func (x *TagAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagAddRequest.ProtoReflect.Descriptor instead.
func (*TagAddRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{15}
}

func (x *TagAddRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagAddRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type TagAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         bool                   `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagAddResponse) Reset() {
	*x = TagAddResponse{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagAddResponse) ProtoMessage() {}

func (x *TagAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagAddResponse.ProtoReflect.Descriptor instead.
func (*TagAddResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{16}
}

func (x *TagAddResponse) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{17}
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{18}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT to use as Authorization: Bearer <token>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{21}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT to use as Authorization: Bearer <token>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_proto_taskmanager_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_taskmanager_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_taskmanager_proto_rawDescGZIP(), []int{22}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_proto_taskmanager_proto protoreflect.FileDescriptor

const file_api_proto_taskmanager_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/taskmanager.proto\x12\vtaskmanager\"\x92\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12\x19\n" +
	"\bdue_date\x18\x05 \x01(\x03R\adueDate\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12!\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\x03R\vcompletedAt\"\x93\x01\n" +
	"\x0eAddTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12\x19\n" +
	"\bdue_date\x18\x04 \x01(\x03R\adueDate\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"8\n" +
	"\x0fAddTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.taskmanager.TaskR\x04task\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"8\n" +
	"\x0fGetTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.taskmanager.TaskR\x04task\"\xa8\x01\n" +
	"\x10ListTasksRequest\x12/\n" +
	"\x06filter\x18\x01 \x01(\x0e2\x17.taskmanager.ListFilterR\x06filter\x12,\n" +
	"\asort_by\x18\x02 \x01(\x0e2\x13.taskmanager.SortByR\x06sortBy\x12\x1b\n" +
	"\tdue_today\x18\x03 \x01(\bR\bdueToday\x12\x18\n" +
	"\aoverdue\x18\x04 \x01(\bR\aoverdue\"U\n" +
	"\x11ListTasksResponse\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.taskmanager.TaskR\x05tasks\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"=\n" +
	"\x13UpdateStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x16\n" +
	"\x14UpdateStatusResponse\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x14\n" +
	"\x12DeleteTaskResponse\"\x80\x02\n" +
	"\x0fEditTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x04 \x01(\tH\x02R\bpriority\x88\x01\x01\x12\x1e\n" +
	"\bdue_date\x18\x05 \x01(\x03H\x03R\adueDate\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x06 \x01(\tH\x04R\x06status\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_priorityB\v\n" +
	"\t_due_dateB\t\n" +
	"\a_status\"\x12\n" +
	"\x10EditTaskResponse\".\n" +
	"\x12SearchTasksRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\">\n" +
	"\x13SearchTasksResponse\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.taskmanager.TaskR\x05tasks\"1\n" +
	"\rTagAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\"&\n" +
	"\x0eTagAddResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\bR\x05added\"\x0e\n" +
	"\fResetRequest\"\x0f\n" +
	"\rResetResponse\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"(\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token*m\n" +
	"\n" +
	"ListFilter\x12\x1b\n" +
	"\x17LIST_FILTER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLIST_FILTER_ALL\x10\x01\x12\x14\n" +
	"\x10LIST_FILTER_DONE\x10\x02\x12\x17\n" +
	"\x13LIST_FILTER_PENDING\x10\x03*]\n" +
	"\x06SortBy\x12\x17\n" +
	"\x13SORT_BY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSORT_BY_CREATED\x10\x01\x12\x0f\n" +
	"\vSORT_BY_DUE\x10\x02\x12\x14\n" +
	"\x10SORT_BY_PRIORITY\x10\x032\x96\x01\n" +
	"\vAuthService\x12G\n" +
	"\bRegister\x12\x1c.taskmanager.RegisterRequest\x1a\x1d.taskmanager.RegisterResponse\x12>\n" +
	"\x05Login\x12\x19.taskmanager.LoginRequest\x1a\x1a.taskmanager.LoginResponse2\xa7\x05\n" +
	"\vTaskService\x12D\n" +
	"\aAddTask\x12\x1b.taskmanager.AddTaskRequest\x1a\x1c.taskmanager.AddTaskResponse\x12D\n" +
	"\aGetTask\x12\x1b.taskmanager.GetTaskRequest\x1a\x1c.taskmanager.GetTaskResponse\x12J\n" +
	"\tListTasks\x12\x1d.taskmanager.ListTasksRequest\x1a\x1e.taskmanager.ListTasksResponse\x12S\n" +
	"\fUpdateStatus\x12 .taskmanager.UpdateStatusRequest\x1a!.taskmanager.UpdateStatusResponse\x12M\n" +
	"\n" +
	"DeleteTask\x12\x1e.taskmanager.DeleteTaskRequest\x1a\x1f.taskmanager.DeleteTaskResponse\x12G\n" +
	"\bEditTask\x12\x1c.taskmanager.EditTaskRequest\x1a\x1d.taskmanager.EditTaskResponse\x12P\n" +
	"\vSearchTasks\x12\x1f.taskmanager.SearchTasksRequest\x1a .taskmanager.SearchTasksResponse\x12A\n" +
	"\x06TagAdd\x12\x1a.taskmanager.TagAddRequest\x1a\x1b.taskmanager.TagAddResponse\x12>\n" +
	"\x05Reset\x12\x19.taskmanager.ResetRequest\x1a\x1a.taskmanager.ResetResponseB\x17Z\x15taskmanager/api/protob\x06proto3"

var (
	file_api_proto_taskmanager_proto_rawDescOnce sync.Once
	file_api_proto_taskmanager_proto_rawDescData []byte
)

func file_api_proto_taskmanager_proto_rawDescGZIP() []byte {
	file_api_proto_taskmanager_proto_rawDescOnce.Do(func() {
		file_api_proto_taskmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_taskmanager_proto_rawDesc), len(file_api_proto_taskmanager_proto_rawDesc)))
	})
	return file_api_proto_taskmanager_proto_rawDescData
}

var file_api_proto_taskmanager_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_taskmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_taskmanager_proto_goTypes = []any{
	(ListFilter)(0),              // 0: taskmanager.ListFilter
	(SortBy)(0),                  // 1: taskmanager.SortBy
	(*Task)(nil),                 // 2: taskmanager.Task
	(*AddTaskRequest)(nil),       // 3: taskmanager.AddTaskRequest
	(*AddTaskResponse)(nil),      // 4: taskmanager.AddTaskResponse
	(*GetTaskRequest)(nil),       // 5: taskmanager.GetTaskRequest
	(*GetTaskResponse)(nil),      // 6: taskmanager.GetTaskResponse
	(*ListTasksRequest)(nil),     // 7: taskmanager.ListTasksRequest
	(*ListTasksResponse)(nil),    // 8: taskmanager.ListTasksResponse
	(*UpdateStatusRequest)(nil),  // 9: taskmanager.UpdateStatusRequest
	(*UpdateStatusResponse)(nil), // 10: taskmanager.UpdateStatusResponse
	(*DeleteTaskRequest)(nil),    // 11: taskmanager.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),   // 12: taskmanager.DeleteTaskResponse
	(*EditTaskRequest)(nil),      // 13: taskmanager.EditTaskRequest
	(*EditTaskResponse)(nil),     // 14: taskmanager.EditTaskResponse
	(*SearchTasksRequest)(nil),   // 15: taskmanager.SearchTasksRequest
	(*SearchTasksResponse)(nil),  // 16: taskmanager.SearchTasksResponse
	(*TagAddRequest)(nil),        // 17: taskmanager.TagAddRequest
	(*TagAddResponse)(nil),       // 18: taskmanager.TagAddResponse
	(*ResetRequest)(nil),         // 19: taskmanager.ResetRequest
	(*ResetResponse)(nil),        // 20: taskmanager.ResetResponse
	(*RegisterRequest)(nil),      // 21: taskmanager.RegisterRequest
	(*RegisterResponse)(nil),     // 22: taskmanager.RegisterResponse
	(*LoginRequest)(nil),         // 23: taskmanager.LoginRequest
	(*LoginResponse)(nil),        // 24: taskmanager.LoginResponse
}
var file_api_proto_taskmanager_proto_depIdxs = []int32{
	2,  // 0: taskmanager.AddTaskResponse.task:type_name -> taskmanager.Task
	2,  // 1: taskmanager.GetTaskResponse.task:type_name -> taskmanager.Task
	0,  // 2: taskmanager.ListTasksRequest.filter:type_name -> taskmanager.ListFilter
	1,  // 3: taskmanager.ListTasksRequest.sort_by:type_name -> taskmanager.SortBy
	2,  // 4: taskmanager.ListTasksResponse.tasks:type_name -> taskmanager.Task
	2,  // 5: taskmanager.SearchTasksResponse.tasks:type_name -> taskmanager.Task
	21, // 6: taskmanager.AuthService.Register:input_type -> taskmanager.RegisterRequest
	23, // 7: taskmanager.AuthService.Login:input_type -> taskmanager.LoginRequest
	3,  // 8: taskmanager.TaskService.AddTask:input_type -> taskmanager.AddTaskRequest
	5,  // 9: taskmanager.TaskService.GetTask:input_type -> taskmanager.GetTaskRequest
	7,  // 10: taskmanager.TaskService.ListTasks:input_type -> taskmanager.ListTasksRequest
	9,  // 11: taskmanager.TaskService.UpdateStatus:input_type -> taskmanager.UpdateStatusRequest
	11, // 12: taskmanager.TaskService.DeleteTask:input_type -> taskmanager.DeleteTaskRequest
	13, // 13: taskmanager.TaskService.EditTask:input_type -> taskmanager.EditTaskRequest
	15, // 14: taskmanager.TaskService.SearchTasks:input_type -> taskmanager.SearchTasksRequest
	17, // 15: taskmanager.TaskService.TagAdd:input_type -> taskmanager.TagAddRequest
	19, // 16: taskmanager.TaskService.Reset:input_type -> taskmanager.ResetRequest
	22, // 17: taskmanager.AuthService.Register:output_type -> taskmanager.RegisterResponse
	24, // 18: taskmanager.AuthService.Login:output_type -> taskmanager.LoginResponse
	4,  // 19: taskmanager.TaskService.AddTask:output_type -> taskmanager.AddTaskResponse
	6,  // 20: taskmanager.TaskService.GetTask:output_type -> taskmanager.GetTaskResponse
	8,  // 21: taskmanager.TaskService.ListTasks:output_type -> taskmanager.ListTasksResponse
	10, // 22: taskmanager.TaskService.UpdateStatus:output_type -> taskmanager.UpdateStatusResponse
	12, // 23: taskmanager.TaskService.DeleteTask:output_type -> taskmanager.DeleteTaskResponse
	14, // 24: taskmanager.TaskService.EditTask:output_type -> taskmanager.EditTaskResponse
	16, // 25: taskmanager.TaskService.SearchTasks:output_type -> taskmanager.SearchTasksResponse
	18, // 26: taskmanager.TaskService.TagAdd:output_type -> taskmanager.TagAddResponse
	20, // 27: taskmanager.TaskService.Reset:output_type -> taskmanager.ResetResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_taskmanager_proto_init() }
func file_api_proto_taskmanager_proto_init() {
	if File_api_proto_taskmanager_proto != nil {
		return
	}
	file_api_proto_taskmanager_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_taskmanager_proto_rawDesc), len(file_api_proto_taskmanager_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_taskmanager_proto_goTypes,
		DependencyIndexes: file_api_proto_taskmanager_proto_depIdxs,
		EnumInfos:         file_api_proto_taskmanager_proto_enumTypes,
		MessageInfos:      file_api_proto_taskmanager_proto_msgTypes,
	}.Build()
	File_api_proto_taskmanager_proto = out.File
	file_api_proto_taskmanager_proto_goTypes = nil
	file_api_proto_taskmanager_proto_depIdxs = nil
}
